### PR TITLE
Implement groupchat event propagation

### PR DESCRIPTION
**Pull request by galfert**
This sends a groupchat activity to the client.

### CODE REVIEW

**Comment by silverbucket** [comment]
(y) looks good

**Comment by skddc** [comment]
Cool.

So chat messages are the only type of groupchat "event"? The term "event" would suggest to me that this could be other events as well. If not, why not call it "groupchat message" instead?

**Comment by galfert** [comment]
As far as I've seen, it's only chat messages in a room that trigger that event.

If you mean the function name itself, that needs to be named that way, as it's an event handler called by `simple-xmpp`.

**Comment by skddc** [comment]
Ah ok. Thanks.

**Pull request merged**
