### PR TITLE
Fix joining MUC channels

### PR DESCRIPTION
**Pull request by galfert**
The join stanza requires a room nick. See https://xmpp.org/extensions/xep-0045.html#registrar-querytypes-join for details.

@silverbucket I couldn't figure out how to test a stub to be called with certain parameters. Any hints about that?

### CODE REVIEW

**Comment by silverbucket** [comment]
@galfert what do you mean by stub and parameters? :) Can you give me an example?

**Comment by galfert** [comment]
@silverbucket for example, in [this line](https://github.com/sockethub/sockethub-platform-xmpp/blob/ef95b36e9540e9e745cc12616c24e975de629940/test/xmpp-suite.js#L181), you test that your stub gets called once. I would also like to test that it gets called with certain parameters. Is that possible?

Something like `test.assert(env.xmpp.join.calledWith('param 1', 'param 2'), true);`.

**Comment by silverbucket** [comment]
@galfert do you think this might be what you're looking for? https://github.com/silverbucket/jaribu#mocks-and-stubs

If not, maybe you could suggest the interface for how you'd like it to work?

**Comment by skddc** [comment]
@silverbucket If you carefully read @galfert's question again, you'll see that he's asking for functionality not documented in the link you responded with. He needs to check for the actual content of the function params/args (as opposed to just checking for "called" or "number of times called".

If it doesn't exist yet, then his code example would be a good suggestion for the API.

**Comment by silverbucket** [comment]
@skddc I understand that he needs to get the params of the function called, rather than the number of times it was called, if you read the example I linked to:

```javascript
var mock = new this.Stub(function(p1, p2) {
    console.log('hello world');
  });

  mock.called;  // false

  mock.numCalled;  // 0

  mock();  // hello world
```

When `mock()` is called, `hello world` is logged, meaning you have access to the params as well. I wasn't totally sure if this is what @galfert needs, as maybe the context in which he's testing won't allow him to use it during the creation of the Stub, but it's a starting point for discussing a possible new API feature if needed.

**Comment by galfert** [comment]
Looks like I didn't fully understand the example, maybe because `p1` and `p2` weren't used anywhere.

I think it could be made a little clearer. Instead of logging "hello world", you could log something like `console.log("mock was called with", p1, p2);`.

I did not create the mock myself, but it was already part of the test suite. I will see if I can adapt it to my needs and will let you know if it worked.

**Comment by skddc** [comment]
Having to manually return an object and then parse it in tests is definitely not a clean or convenient way of doing this. A proper assertion for `calledWith` would be *much* better imo.

**Comment by galfert** [comment]
I added a test the checks for the correct parameter. This is ready for review/merge now.

**Comment by silverbucket** [comment]
@galfert I see how this makes the mock less useful, but also the test code itself doesn't look bad. Merging

**Pull request merged**
